
disabled_rules:
  - trailing_whitespace

# Rule Config
line_length: 150
identifier_name:
  min_length: 1
  max_length:
    warning: 40
    error: 60
type_name:
  min_length: 3
  max_length:
    warning: 80
    error: 100

# General Config
excluded:
  - Carthage
  - DuckDuckGo/UserText.swift

