appId: com.duckduckgo.mobile.ios
---

- scroll
- scroll
- scroll
- assertVisible: All debug options
- tapOn: All debug options
- tapOn: Internal User State
- tapOn: Settings
- tapOn: Done
- tapOn: Settings