fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "c7ddc28b-25d3-424d-b688-e693165a4521"

default_platform :ios

lane :release do 

  # if signing fails then check we have certificate and provisioning profiles installed
  gym(
    scheme: "DuckDuckGo",
    export_method: "app-store"
  )

  # don't submit for review until we're happy the build job works
  deliver(
    submit_for_review: false,
    automatic_release: false, 
    phased_release: true,
    screenshots_path: "screenshots",
    username: "office@duckduckgo.com"
  )

end

lane :screenshots do

  gym(
    scheme: "AppScreenshots",
    export_method: "development"
  )

   reset_simulators
   snapshot

end

