name: Promote TestFlight to App Store

on: 
  workflow_dispatch: {}
  push:
    branches:
      - kieran/release-changes

jobs:
  promote-testflight-to-appstore:
    runs-on: macos-14

    steps:
    - name: Check out the code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}
        sparse-checkout: |
          .github
          Gemfile
          Gemfile.lock
          fastlane
          scripts

    - name: Set up fastlane
      run: bundle install

    - name: Promote TestFlight to App Store
      env:
        APPLE_API_KEY_BASE64: ${{ secrets.APPLE_API_KEY_BASE64 }}
        APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
        APPLE_API_KEY_ISSUER: ${{ secrets.APPLE_API_KEY_ISSUER }}
      run: |
        git config --global user.name "Dax the Duck"
        git config --global user.email "dax@duckduckgo.com"
        bundle exec fastlane promote_latest_testflight_to_appstore alpha:true
        bundle exec fastlane promote_latest_testflight_to_appstore
  
