name: Sync-End-to-End tests

on:
  workflow_dispatch
  #schedule:
  #  - cron: '0 4 * * *' # run at 4 AM UTC

jobs:
  end-to-end-tests:
    name: Sync End to end Tests
    runs-on: macos-13

    steps:
    - name: Check out the code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set cache key hash
      run: |
         has_only_tags=$(jq '[ .object.pins[].state | has("version") ] | all' DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved)
         if [[ "$has_only_tags" == "true" ]]; then
           echo "cache_key_hash=${{ hashFiles('DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}" >> $GITHUB_ENV
         else
           echo "Package.resolved contains dependencies specified by branch or commit, skipping cache."
         fi

    - name: Cache SPM
      if: env.cache_key_hash
      uses: actions/cache@v3
      with:
        path: DerivedData/SourcePackages
        key: ${{ runner.os }}-spm-${{ env.cache_key_hash }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_$(<.xcode-version).app/Contents/Developer

    - name: Build for tests
      run: |
        set -o pipefail && xcodebuild \
          -scheme "DuckDuckGo" \
          -destination "platform=iOS Simulator,name=iPhone 14,OS=16.4" \
          -derivedDataPath "DerivedData" \
        | tee xcodebuild.log
    
    - name: Create test account for Sync and return the recovery code
      uses: duckduckgo/sync_crypto/action@main
      id: sync-recovery-code
      with:
        debug: true
    
    - name: Sync e2e tests
      uses: mobile-dev-inc/action-maestro-cloud@v1.6.0
      with:
        api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
        app-file: DerivedData/Build/Products/Debug-iphonesimulator/DuckDuckGo.app
        workspace: .maestro
        include-tags: sync
        env: |
            CODE=${{ steps.sync-recovery-code.outputs.recovery-code }}
    
    
