name: Run unit tests

on: 
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]


jobs:
  unit-tests:

    runs-on: macos-11

    steps:
    - name: Check out the code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Run unit tests
      run: |
        set -o pipefail && \
        xcodebuild test \
          -scheme "DuckDuckGo" \
          -destination "platform=iOS Simulator,name=iPhone 8" \
          | xcpretty -r junit -o unittests.xml

    - name: Publish Unit Tests Report
      uses: mikepenz/action-junit-report@v3
      if: always() # always run even if the previous step fails
      with:
        report_paths: unittests.xml

